# Generated by Django 5.1.3 on 2025-03-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(related_name='movies', to='core.video'),
        ),
    ]
